### ISSUE TITLE
Whats the difference from cordova-plugin-hostedwebapp?

### ISSUE THREAD

**Issue by gajus** [TruckMovers/cordova-plugin-remote-injection#27]
[`cordova-plugin-hostedwebapp`](https://github.com/manifoldjs/ManifoldCordova) appears to be aiming to achieve more or less the same goals. Unlike `cordova-plugin-remote-injection`, it has handy features such as a page that can be displayed when application is offline.

Was there a particular reason to create this plugin?

I am only wondering because I am researching which plugin to use.

**Comment by bradleyjames** [comment]
This plugin started 2 years ago.  I don't recall exactly why I didn't use cordova-plugin-hostedwebapp.  But I do know that when I was researching I didn't find any apps that worked in the manner we were looking for and thus this plugin was born.

I highly recommend evaluating cordovan-plugin-hostedwebapp because this plugin won't be receiving updates.  I'll patch bugs but I'm no longer using it.  So if it satisfies your use cases I'd say go for it.

**Comment by gajus** [comment]
> I highly recommend evaluating cordovan-plugin-hostedwebapp because this plugin won't be receiving updates. I'll patch bugs but I'm no longer using it. So if it satisfies your use cases I'd say go for it.

If thats the case, it would be nice to add a depreciation notice in favor of selected libraries.

**Comment by gajus** [comment]
Thank you for the update.

**Comment by pauloya** [comment]
Sadly hostedwebapp doesn't seem to have any support anyway, it doesn't build with the latest cordova versions.
I wonder if this plugin survives the test of time better?
Or does anyone know of any other plugin that does a similar job and is up to date?

**Comment by markdon** [comment]
remote-injection works for cordova-android@7.0.0 and cordova-ios@4.5.4, although there are some issues open for people having trouble. It shouldn't be much work to update this plugin if there is a problem with latest and you know a little bit of cordova/ios/android.

A year ago or so I picked remote-injection over hostedwebapp because hostedwebapp seemed to do more that what was needed. remote-injection pretty much just does cordova/js injection with some not-great offline handling. Once Apple finally adds [ServiceWorker to WKWebView](https://stackoverflow.com/questions/49673399/service-workers-unavailable-in-wkwebview-in-ios-11-3), offline can be handled with js.
